version: '3'
services:
  selenium-standalone-server:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
  tests:
    image: 'node:10'
    command: /bin/bash -c 'npm install && npm run test'
    links:
      - selenium-standalone-server
    volumes:
      - ./:/app
    working_dir: /app

